"""
LYLO OS — tactical_vault.py
Elite Tier — Tactical Vault PDF Engine
Version: 1.0.0

Generates high-fidelity, persona-specific incident reports as PDFs.
Supports 4 persona report types: doctor, lawyer, wealth, mechanic.
Includes GPS/timestamp/weather metadata, image embeds, and AI bodyguard summary.

Public API:
    generate_tactical_report(report_data: TacticalReportData) -> bytes
        Returns PDF as raw bytes. Store or stream directly.

    send_report_to_pro(pdf_bytes, recipient_email, sender_name,
                       persona_id, subject_override=None) -> bool
        Emails the PDF to a third party (lawyer, doctor, etc.)

    build_incident_prompt(persona_id, incident_description,
                          metadata, image_count) -> str
        Returns the OpenAI prompt for the AI Bodyguard Summary section.

Drop-in usage in main.py:
    from tactical_vault import generate_tactical_report, send_report_to_pro, TacticalReportData
"""

from __future__ import annotations

import io
import logging
import os
import smtplib
import ssl
from dataclasses import dataclass, field
from datetime import datetime, timezone
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image as RLImage,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.pdfgen import canvas as rl_canvas

log = logging.getLogger("LYLO.TacticalVault")

# =============================================================================
# BRAND COLORS
# =============================================================================
LYLO_BLACK    = colors.HexColor("#0A0A0A")
LYLO_WHITE    = colors.HexColor("#F5F5F5")
LYLO_BLUE     = colors.HexColor("#3B82F6")
LYLO_RED      = colors.HexColor("#EF4444")
LYLO_GREEN    = colors.HexColor("#22C55E")
LYLO_GOLD     = colors.HexColor("#EAB308")
LYLO_INDIGO   = colors.HexColor("#6366F1")
LYLO_GRAY_D   = colors.HexColor("#1C1C1C")   # dark card bg
LYLO_GRAY_M   = colors.HexColor("#2A2A2A")   # mid card bg
LYLO_GRAY_L   = colors.HexColor("#3F3F3F")   # table row alt
LYLO_GRAY_T   = colors.HexColor("#888888")   # subdued text

# Persona accent color map
PERSONA_COLORS: dict[str, colors.HexColor] = {
    "doctor":   LYLO_RED,
    "lawyer":   LYLO_GOLD,
    "wealth":   LYLO_GREEN,
    "mechanic": colors.HexColor("#9CA3AF"),  # gray
    "guardian": LYLO_BLUE,
    "default":  LYLO_BLUE,
}

PERSONA_LABELS: dict[str, str] = {
    "doctor":   "MEDICAL TRIAGE REPORT",
    "lawyer":   "LEGAL EVIDENCE DOSSIER",
    "wealth":   "CONSUMER DISPUTE BRIEF",
    "mechanic": "VEHICLE DIAGNOSTIC REPORT",
    "guardian": "SECURITY INCIDENT REPORT",
    "default":  "TACTICAL INCIDENT REPORT",
}

PERSONA_ICONS: dict[str, str] = {
    "doctor":   "MEDICAL GUIDE",
    "lawyer":   "LEGAL SHIELD",
    "wealth":   "FINANCE CHIEF",
    "mechanic": "MASTER FIXER",
    "guardian": "SECURITY LEAD",
    "default":  "BODYGUARD COUNCIL",
}

# =============================================================================
# DATA MODEL
# =============================================================================

@dataclass
class TacticalReportData:
    """
    All data needed to generate a Tactical Vault PDF.
    Passed from the /generate-report FastAPI endpoint.
    """
    # ── User Context ─────────────────────────────────────────────────────────
    user_name:              str   = "Unknown"
    user_email:             str   = ""
    emergency_contact_name: str   = ""
    emergency_contact_phone: str  = ""

    # ── Incident ─────────────────────────────────────────────────────────────
    persona_id:             str   = "guardian"
    incident_title:         str   = "Incident Report"
    incident_description:   str   = ""

    # ── Metadata (auto-collected by frontend) ─────────────────────────────────
    timestamp:              str   = ""          # ISO string, e.g. "2025-02-24T14:33:00Z"
    gps_latitude:           str   = ""
    gps_longitude:          str   = ""
    gps_address:            str   = ""
    weather_condition:      str   = ""
    weather_temp_f:         str   = ""
    device_model:           str   = ""

    # ── AI Bodyguard Summary ─────────────────────────────────────────────────
    bodyguard_summary:      str   = ""          # Pre-generated by OpenAI before PDF call

    # ── Persona-Specific Fields ───────────────────────────────────────────────
    # Doctor
    pain_scale:             str   = ""          # 1-10
    pain_duration:          str   = ""
    pain_location:          str   = ""
    symptoms:               list  = field(default_factory=list)
    prior_conditions:       str   = ""

    # Lawyer
    witness_names:          list  = field(default_factory=list)
    opposing_party:         str   = ""
    police_report_number:   str   = ""
    silence_protocol_used:  bool  = True

    # Wealth
    merchant_name:          str   = ""
    transaction_amount:     str   = ""
    dispute_reason:         str   = ""
    consumer_rights_note:   str   = ""

    # Mechanic
    vehicle_year:           str   = ""
    vehicle_make:           str   = ""
    vehicle_model:          str   = ""
    obd_codes:              list  = field(default_factory=list)
    dealer_quote:           str   = ""
    fair_market_estimate:   str   = ""
    repair_description:     str   = ""

    # ── Images ────────────────────────────────────────────────────────────────
    image_bytes_list:       list  = field(default_factory=list)  # list of bytes objects
    image_captions:         list  = field(default_factory=list)  # parallel list of caption strings


# =============================================================================
# STYLE SHEET
# =============================================================================

def _build_styles() -> dict:
    base = getSampleStyleSheet()

    s = {}

    s["report_title"] = ParagraphStyle(
        "report_title",
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=LYLO_WHITE,
        alignment=TA_LEFT,
        spaceAfter=2,
        leading=26,
    )
    s["report_subtitle"] = ParagraphStyle(
        "report_subtitle",
        fontName="Helvetica",
        fontSize=9,
        textColor=LYLO_GRAY_T,
        alignment=TA_LEFT,
        spaceAfter=0,
        tracking=80,
    )
    s["section_header"] = ParagraphStyle(
        "section_header",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=LYLO_GRAY_T,
        alignment=TA_LEFT,
        spaceBefore=18,
        spaceAfter=6,
        tracking=120,
    )
    s["body"] = ParagraphStyle(
        "body",
        fontName="Helvetica",
        fontSize=10,
        textColor=LYLO_WHITE,
        alignment=TA_LEFT,
        spaceAfter=6,
        leading=15,
    )
    s["body_muted"] = ParagraphStyle(
        "body_muted",
        fontName="Helvetica",
        fontSize=9,
        textColor=LYLO_GRAY_T,
        alignment=TA_LEFT,
        spaceAfter=4,
        leading=13,
    )
    s["bodyguard_summary"] = ParagraphStyle(
        "bodyguard_summary",
        fontName="Helvetica-Oblique",
        fontSize=11,
        textColor=LYLO_WHITE,
        alignment=TA_LEFT,
        spaceAfter=8,
        leading=17,
        leftIndent=12,
        rightIndent=12,
    )
    s["label"] = ParagraphStyle(
        "label",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=LYLO_GRAY_T,
        alignment=TA_LEFT,
        spaceAfter=2,
        tracking=80,
    )
    s["value"] = ParagraphStyle(
        "value",
        fontName="Helvetica",
        fontSize=10,
        textColor=LYLO_WHITE,
        alignment=TA_LEFT,
        spaceAfter=10,
        leading=14,
    )
    s["alert"] = ParagraphStyle(
        "alert",
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=LYLO_RED,
        alignment=TA_LEFT,
        spaceAfter=6,
        leading=14,
    )
    s["caption"] = ParagraphStyle(
        "caption",
        fontName="Helvetica-Oblique",
        fontSize=8,
        textColor=LYLO_GRAY_T,
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    s["footer"] = ParagraphStyle(
        "footer",
        fontName="Helvetica",
        fontSize=7,
        textColor=LYLO_GRAY_T,
        alignment=TA_CENTER,
    )
    s["obd_code"] = ParagraphStyle(
        "obd_code",
        fontName="Courier-Bold",
        fontSize=11,
        textColor=LYLO_RED,
        alignment=TA_LEFT,
        spaceAfter=4,
    )

    return s


# =============================================================================
# PAGE CANVAS — dark background + header/footer on every page
# =============================================================================

class _DarkPageCanvas:
    """
    Wraps reportlab's canvas to draw a dark background, colored header stripe,
    and footer on every page.
    """
    def __init__(self, persona_id: str, user_name: str, report_id: str):
        self.persona_id  = persona_id
        self.user_name   = user_name
        self.report_id   = report_id
        self.accent      = PERSONA_COLORS.get(persona_id, PERSONA_COLORS["default"])

    def __call__(self, c: rl_canvas.Canvas, doc):
        W, H = letter
        c.saveState()

        # Full-page dark background
        c.setFillColor(LYLO_BLACK)
        c.rect(0, 0, W, H, fill=1, stroke=0)

        # Top accent stripe
        c.setFillColor(self.accent)
        c.rect(0, H - 0.35 * inch, W, 0.35 * inch, fill=1, stroke=0)

        # LYLO OS label in stripe
        c.setFillColor(LYLO_BLACK)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(0.5 * inch, H - 0.24 * inch, "LYLO OS  ·  TACTICAL VAULT  ·  ELITE TIER")

        # Report ID top-right
        c.setFont("Helvetica", 7)
        c.drawRightString(W - 0.5 * inch, H - 0.24 * inch, f"ID: {self.report_id}")

        # Bottom footer line
        c.setStrokeColor(LYLO_GRAY_M)
        c.setLineWidth(0.5)
        c.line(0.5 * inch, 0.45 * inch, W - 0.5 * inch, 0.45 * inch)

        # Footer text
        c.setFillColor(LYLO_GRAY_T)
        c.setFont("Helvetica", 7)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        c.drawString(0.5 * inch, 0.28 * inch,
                     f"CONFIDENTIAL — {self.user_name.upper()} — Generated {ts}")
        c.drawRightString(W - 0.5 * inch, 0.28 * inch,
                          f"Page {doc.page}")

        c.restoreState()


# =============================================================================
# SECTION BUILDERS
# =============================================================================

def _divider(accent: colors.HexColor, story: list):
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=accent, spaceAfter=4))


def _section_header(title: str, s: dict, story: list):
    story.append(Paragraph(title.upper(), s["section_header"]))


def _kv_table(pairs: list[tuple[str, str]], s: dict,
               accent: colors.HexColor) -> Table:
    """
    Renders a two-column key/value table with dark styling.
    pairs: list of (label, value) tuples
    """
    data = []
    for label, value in pairs:
        data.append([
            Paragraph(label.upper(), s["label"]),
            Paragraph(str(value) if value else "—", s["value"]),
        ])

    col_widths = [1.6 * inch, 5.4 * inch]
    t = Table(data, colWidths=col_widths, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), LYLO_GRAY_D),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LYLO_GRAY_D, LYLO_GRAY_M]),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING",   (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 7),
        ("LINEBELOW",    (0, 0), (-1, -1), 0.3, LYLO_GRAY_L),
        ("BOX",          (0, 0), (-1, -1), 0.5, accent),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def _build_cover_block(data: TacticalReportData, s: dict,
                        accent: colors.HexColor, story: list):
    """Cover section: persona label, incident title, user context."""
    persona_label = PERSONA_LABELS.get(data.persona_id, PERSONA_LABELS["default"])
    persona_icon  = PERSONA_ICONS.get(data.persona_id, PERSONA_ICONS["default"])

    story.append(Spacer(1, 0.2 * inch))

    # Persona seat label
    story.append(Paragraph(persona_icon, s["report_subtitle"]))
    story.append(Spacer(1, 4))

    # Main incident title
    story.append(Paragraph(data.incident_title or "Incident Report", s["report_title"]))
    story.append(Spacer(1, 2))
    story.append(Paragraph(persona_label, s["report_subtitle"]))
    story.append(Spacer(1, 0.15 * inch))
    _divider(accent, story)

    # User + emergency contact
    _section_header("PROTECTED PARTY", s, story)
    pairs = [
        ("Name",              data.user_name),
        ("Contact Email",     data.user_email or "—"),
        ("Emergency Contact", data.emergency_contact_name or "—"),
        ("Emergency Phone",   data.emergency_contact_phone or "—"),
    ]
    story.append(_kv_table(pairs, s, accent))


def _build_metadata_block(data: TacticalReportData, s: dict,
                           accent: colors.HexColor, story: list):
    """Auto-collected GPS, timestamp, weather metadata."""
    _section_header("INCIDENT METADATA — AUTO-RECORDED", s, story)

    # Format timestamp
    ts_display = data.timestamp
    if ts_display:
        try:
            dt = datetime.fromisoformat(data.timestamp.replace("Z", "+00:00"))
            ts_display = dt.strftime("%B %d, %Y at %I:%M %p UTC")
        except Exception:
            pass

    # GPS line
    gps_display = "—"
    if data.gps_latitude and data.gps_longitude:
        gps_display = f"{data.gps_latitude}, {data.gps_longitude}"
        if data.gps_address:
            gps_display += f"  ·  {data.gps_address}"

    # Weather
    weather_display = "—"
    if data.weather_condition:
        weather_display = data.weather_condition
        if data.weather_temp_f:
            weather_display += f"  ·  {data.weather_temp_f}°F"

    pairs = [
        ("Timestamp",  ts_display or "—"),
        ("GPS",        gps_display),
        ("Weather",    weather_display),
        ("Device",     data.device_model or "—"),
    ]
    story.append(_kv_table(pairs, s, accent))


def _build_bodyguard_summary(data: TacticalReportData, s: dict,
                              accent: colors.HexColor, story: list):
    """AI-generated plain-English incident summary."""
    if not data.bodyguard_summary:
        return

    _section_header("BODYGUARD SUMMARY — AI ANALYSIS", s, story)

    # Bordered card for the summary
    summary_text = data.bodyguard_summary.replace("\n", "<br/>")
    summary_para = Paragraph(summary_text, s["bodyguard_summary"])

    card = Table(
        [[summary_para]],
        colWidths=[7.0 * inch],
    )
    card.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), LYLO_GRAY_D),
        ("BOX",          (0, 0), (-1, -1), 1.0, accent),
        ("LEFTPADDING",  (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING",   (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 12),
        ("LINEABOVE",    (0, 0), (-1, 0),  2.0, accent),
    ]))
    story.append(card)
    story.append(Spacer(1, 8))


def _build_images_block(data: TacticalReportData, s: dict,
                         accent: colors.HexColor, story: list):
    """Embeds high-res images with captions."""
    if not data.image_bytes_list:
        return

    _section_header(f"VISUAL EVIDENCE — {len(data.image_bytes_list)} IMAGE(S) ATTACHED", s, story)

    for i, img_bytes in enumerate(data.image_bytes_list):
        caption = (data.image_captions[i]
                   if i < len(data.image_captions)
                   else f"Evidence Photo {i + 1}")
        try:
            img_buf = io.BytesIO(img_bytes)
            rl_img  = RLImage(img_buf, width=6.5 * inch, height=4.0 * inch,
                              kind="proportional")

            # Border frame
            img_table = Table([[rl_img]], colWidths=[6.6 * inch])
            img_table.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), LYLO_GRAY_D),
                ("BOX",           (0, 0), (-1, -1), 1.0, accent),
                ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
                ("TOPPADDING",    (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(img_table)
            story.append(Paragraph(
                f"FIGURE {i + 1}: {caption.upper()}", s["caption"]
            ))
        except Exception as e:
            log.warning(f"[Vault] Image {i + 1} embed failed: {e}")
            story.append(Paragraph(
                f"[Image {i + 1} could not be embedded — file may be corrupted]",
                s["body_muted"]
            ))


# =============================================================================
# PERSONA-SPECIFIC SECTION BUILDERS
# =============================================================================

def _build_doctor_section(data: TacticalReportData, s: dict,
                           accent: colors.HexColor, story: list):
    story.append(PageBreak())
    _section_header("CLINICAL TRIAGE SUMMARY", s, story)

    # Pain assessment card
    pairs = [
        ("Pain Scale",      f"{data.pain_scale} / 10" if data.pain_scale else "—"),
        ("Duration",        data.pain_duration or "—"),
        ("Location",        data.pain_location or "—"),
        ("Prior Conditions", data.prior_conditions or "None reported"),
    ]
    story.append(_kv_table(pairs, s, accent))

    # Symptoms list
    if data.symptoms:
        _section_header("REPORTED SYMPTOMS", s, story)
        for i, symptom in enumerate(data.symptoms, 1):
            story.append(Paragraph(f"{i}. {symptom}", s["body"]))
        story.append(Spacer(1, 6))

    # Incident description
    if data.incident_description:
        _section_header("PATIENT STATEMENT", s, story)
        story.append(Paragraph(data.incident_description, s["body"]))

    # Visual evidence
    _build_images_block(data, s, accent, story)

    # Doctor advisory
    _divider(accent, story)
    story.append(Paragraph(
        "ADVISORY: This report documents the patient's self-reported symptoms at the "
        "time of the incident. It is not a clinical diagnosis. Present this document "
        "to your physician or ER staff as a first-contact triage brief.",
        s["body_muted"]
    ))


def _build_lawyer_section(data: TacticalReportData, s: dict,
                           accent: colors.HexColor, story: list):
    story.append(PageBreak())
    _section_header("LEGAL EVIDENCE CHAIN", s, story)

    pairs = [
        ("Opposing Party",      data.opposing_party or "—"),
        ("Police Report No.",   data.police_report_number or "Not filed"),
        ("Silence Protocol",    "ACTIVATED — No statements made to opposing party"
                                if data.silence_protocol_used
                                else "Not activated — review statements made"),
    ]
    story.append(_kv_table(pairs, s, accent))

    # Witnesses
    if data.witness_names:
        _section_header("WITNESS REGISTRY", s, story)
        for i, w in enumerate(data.witness_names, 1):
            story.append(Paragraph(f"{i}. {w}", s["body"]))
        story.append(Spacer(1, 6))

    # Incident narrative
    if data.incident_description:
        _section_header("INCIDENT NARRATIVE — CLIENT STATEMENT", s, story)
        story.append(Paragraph(data.incident_description, s["body"]))

    # Visual evidence
    _build_images_block(data, s, accent, story)

    # Silence Protocol box
    story.append(PageBreak())
    _section_header("SILENCE PROTOCOL", s, story)
    silence_lines = [
        "1. Do NOT give a recorded statement to any insurance adjuster without counsel.",
        "2. Do NOT sign any release or settlement document at the scene.",
        "3. Do NOT discuss fault, apologize, or speculate about the incident.",
        "4. Direct all parties to your attorney for any questions.",
        "5. Preserve this document as your contemporaneous record of events.",
    ]
    for line in silence_lines:
        story.append(Paragraph(line, s["body"]))

    _divider(accent, story)
    story.append(Paragraph(
        "ADVISORY: This dossier is prepared under attorney-client privilege guidelines "
        "for the sole use of the named party. It is not legal advice. Retain a licensed "
        "attorney to review before taking any legal action.",
        s["body_muted"]
    ))


def _build_wealth_section(data: TacticalReportData, s: dict,
                           accent: colors.HexColor, story: list):
    story.append(PageBreak())
    _section_header("CONSUMER DISPUTE EVIDENCE", s, story)

    pairs = [
        ("Merchant / Party",      data.merchant_name or "—"),
        ("Transaction Amount",    f"${data.transaction_amount}" if data.transaction_amount else "—"),
        ("Dispute Reason",        data.dispute_reason or "—"),
        ("Consumer Rights Note",  data.consumer_rights_note or "—"),
    ]
    story.append(_kv_table(pairs, s, accent))

    # Incident description
    if data.incident_description:
        _section_header("DISPUTE NARRATIVE", s, story)
        story.append(Paragraph(data.incident_description, s["body"]))

    # Visual evidence
    _build_images_block(data, s, accent, story)

    # Dispute escalation ladder
    _section_header("DISPUTE ESCALATION LADDER", s, story)
    steps = [
        ("STEP 1", "Send written dispute to merchant via certified mail. Keep tracking number."),
        ("STEP 2", "File a chargeback with your credit card issuer. Reference this document."),
        ("STEP 3", "File complaint with CFPB (consumerfinance.gov) — free and federally tracked."),
        ("STEP 4", "File with your state Attorney General's consumer protection office."),
        ("STEP 5", "Small claims court. This document serves as your contemporaneous evidence record."),
    ]
    step_data = [[Paragraph(s_label, s["label"]), Paragraph(s_text, s["body"])]
                 for s_label, s_text in steps]
    step_table = Table(step_data, colWidths=[0.9 * inch, 6.1 * inch], hAlign="LEFT")
    step_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), LYLO_GRAY_D),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LYLO_GRAY_D, LYLO_GRAY_M]),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING",   (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 7),
        ("LINEBELOW",    (0, 0), (-1, -1), 0.3, LYLO_GRAY_L),
        ("BOX",          (0, 0), (-1, -1), 0.5, accent),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(step_table)

    _divider(accent, story)
    story.append(Paragraph(
        "ADVISORY: This brief documents your consumer rights dispute evidence. "
        "All federal consumer protection filings are free of charge. "
        "You are not required to accept any settlement without independent review.",
        s["body_muted"]
    ))


def _build_mechanic_section(data: TacticalReportData, s: dict,
                             accent: colors.HexColor, story: list):
    story.append(PageBreak())
    _section_header("VEHICLE DIAGNOSTIC RECORD", s, story)

    vehicle_str = " ".join(filter(None, [
        data.vehicle_year, data.vehicle_make, data.vehicle_model
    ])) or "—"

    pairs = [
        ("Vehicle",           vehicle_str),
        ("Repair Description", data.repair_description or "—"),
        ("Dealer / Shop Quote", f"${data.dealer_quote}" if data.dealer_quote else "—"),
        ("Fair Market Estimate", f"${data.fair_market_estimate}" if data.fair_market_estimate else "—"),
    ]

    # Price delta highlight
    if data.dealer_quote and data.fair_market_estimate:
        try:
            delta = float(data.dealer_quote.replace(",", "")) - \
                    float(data.fair_market_estimate.replace(",", ""))
            if delta > 0:
                pairs.append(("Potential Overcharge", f"${delta:,.2f} above market rate"))
        except (ValueError, TypeError):
            pass

    story.append(_kv_table(pairs, s, accent))

    # OBD-II codes
    if data.obd_codes:
        _section_header("OBD-II FAULT CODES", s, story)
        for code in data.obd_codes:
            story.append(Paragraph(f"  {code}", s["obd_code"]))
        story.append(Spacer(1, 4))
        story.append(Paragraph(
            "Cross-reference these codes at obdii.com or with a second-opinion mechanic "
            "before authorizing any repairs.",
            s["body_muted"]
        ))

    # Incident description
    if data.incident_description:
        _section_header("SYMPTOM DESCRIPTION", s, story)
        story.append(Paragraph(data.incident_description, s["body"]))

    # Visual evidence
    _build_images_block(data, s, accent, story)

    # Negotiation guide
    _section_header("NEGOTIATION PROTOCOL", s, story)
    steps = [
        "Show this document to the service advisor. State you have the market rate.",
        "Request an itemized written estimate before authorizing any work.",
        "If the quote exceeds market by 20%+, ask for a line-by-line justification.",
        "Get a second opinion from an independent shop — this document travels with you.",
        "Never authorize diagnostic fees without a written cap.",
    ]
    for i, step in enumerate(steps, 1):
        story.append(Paragraph(f"{i}. {step}", s["body"]))

    _divider(accent, story)
    story.append(Paragraph(
        "ADVISORY: OBD-II codes and market estimates are reference data only. "
        "Have a licensed mechanic verify all codes before repair authorization.",
        s["body_muted"]
    ))


# =============================================================================
# MAIN PDF GENERATOR
# =============================================================================

def generate_tactical_report(report_data: TacticalReportData) -> bytes:
    """
    Generates a high-fidelity Tactical Vault PDF.

    Args:
        report_data: Fully populated TacticalReportData instance.

    Returns:
        Raw PDF bytes — write to file or stream as HTTP response.

    Usage:
        pdf_bytes = generate_tactical_report(data)
        # Stream as FastAPI response:
        return Response(content=pdf_bytes, media_type="application/pdf",
                        headers={"Content-Disposition": "attachment; filename=lylo_report.pdf"})
    """
    buf    = io.BytesIO()
    W, H   = letter
    margin = 0.5 * inch

    # Unique report ID
    import hashlib, time
    report_id = hashlib.md5(
        f"{report_data.user_email}{time.time()}".encode()
    ).hexdigest()[:10].upper()

    doc = SimpleDocTemplate(
        buf,
        pagesize       = letter,
        leftMargin     = margin,
        rightMargin    = margin,
        topMargin      = 0.65 * inch,    # Leaves room for accent stripe
        bottomMargin   = 0.65 * inch,
        title          = f"LYLO Tactical Vault — {report_data.incident_title}",
        author         = "LYLO OS Tactical Vault",
        subject        = PERSONA_LABELS.get(report_data.persona_id, "Incident Report"),
        creator        = "LYLO OS v31.0",
    )

    accent  = PERSONA_COLORS.get(report_data.persona_id, PERSONA_COLORS["default"])
    s       = _build_styles()
    story   = []

    page_canvas_fn = _DarkPageCanvas(
        persona_id = report_data.persona_id,
        user_name  = report_data.user_name,
        report_id  = report_id,
    )

    # ── Page 1: Cover + Metadata + Bodyguard Summary ─────────────────────────
    _build_cover_block(report_data, s, accent, story)
    _build_metadata_block(report_data, s, accent, story)
    _build_bodyguard_summary(report_data, s, accent, story)

    # For personas that don't have a dedicated section, embed images on page 1
    if report_data.persona_id not in ("doctor", "lawyer", "wealth", "mechanic"):
        _build_images_block(report_data, s, accent, story)
        if report_data.incident_description:
            _section_header("INCIDENT DESCRIPTION", s, story)
            story.append(Paragraph(report_data.incident_description, s["body"]))

    # ── Page 2+: Persona-Specific Section ───────────────────────────────────
    persona = report_data.persona_id
    if persona == "doctor":
        _build_doctor_section(report_data, s, accent, story)
    elif persona == "lawyer":
        _build_lawyer_section(report_data, s, accent, story)
    elif persona == "wealth":
        _build_wealth_section(report_data, s, accent, story)
    elif persona == "mechanic":
        _build_mechanic_section(report_data, s, accent, story)

    # ── Final page: Certification footer ────────────────────────────────────
    story.append(PageBreak())
    story.append(Spacer(1, 1.5 * inch))
    _divider(accent, story)
    story.append(Spacer(1, 0.2 * inch))

    cert_lines = [
        f"This report was generated by LYLO OS Tactical Vault (Elite Tier).",
        f"Report ID: {report_id}",
        f"Protected Party: {report_data.user_name}",
        f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
        f"",
        f"All metadata in this document was recorded automatically at the time of incident.",
        f"This document may be used as contemporaneous evidence in legal, medical,",
        f"insurance, or consumer protection proceedings.",
        f"",
        f"LYLO OS — No one gets left behind.",
    ]
    for line in cert_lines:
        story.append(Paragraph(line, s["footer"] if not line.startswith("LYLO") else ParagraphStyle(
            "cert_brand", fontName="Helvetica-Bold", fontSize=9,
            textColor=accent, alignment=TA_CENTER
        )))
        story.append(Spacer(1, 3))

    doc.build(story, onFirstPage=page_canvas_fn, onLaterPages=page_canvas_fn)
    return buf.getvalue()


# =============================================================================
# SEND TO PRO — EMAIL DISPATCH
# =============================================================================

def send_report_to_pro(
    pdf_bytes:        bytes,
    recipient_email:  str,
    sender_name:      str,
    persona_id:       str,
    subject_override: Optional[str]  = None,
    incident_title:   str            = "Incident Report",
    user_email:       str            = "",
) -> bool:
    """
    Emails the Tactical Vault PDF to a third-party professional
    (lawyer, doctor, insurance agent, etc.) with a single call.

    Requires these environment variables:
        SMTP_HOST       e.g. "smtp.gmail.com"
        SMTP_PORT       e.g. "587"
        SMTP_USER       The sending email address (your system email)
        SMTP_PASSWORD   App password or SMTP credential

    Args:
        pdf_bytes:        Raw PDF bytes from generate_tactical_report()
        recipient_email:  The pro's email address
        sender_name:      The user's display name (for the email body)
        persona_id:       Determines report label in email body
        subject_override: Optional custom subject line
        incident_title:   Incident name for subject line
        user_email:       User's email (for Reply-To header)

    Returns:
        True on successful send, False on failure.
    """
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")

    if not smtp_user or not smtp_pass:
        log.error("[Vault] SMTP credentials not configured — set SMTP_USER and SMTP_PASSWORD.")
        return False

    report_label = PERSONA_LABELS.get(persona_id, "TACTICAL INCIDENT REPORT")
    subject = subject_override or (
        f"LYLO OS — {report_label}: {incident_title} — Sent by {sender_name}"
    )

    # ── Email body ────────────────────────────────────────────────────────────
    body_text = f"""
{report_label}
Sent via LYLO OS Tactical Vault — Elite Tier

From:    {sender_name}
Re:      {incident_title}

This report was generated automatically by LYLO OS at the time of the incident.
It contains:
  - User personal context and emergency contact
  - GPS coordinates, timestamp, and weather metadata
  - High-resolution photographic evidence
  - AI-generated plain-English incident summary
  - {report_label.title()} analysis and recommended next steps

This document is intended for your professional review as part of the
ongoing matter referenced above.

For questions, contact {sender_name} directly (Reply-To included).

—
LYLO OS Tactical Vault
Elite Tier — Confidential Document
""".strip()

    # ── Assemble MIME message ─────────────────────────────────────────────────
    msg = MIMEMultipart()
    msg["From"]     = f"LYLO OS Tactical Vault <{smtp_user}>"
    msg["To"]       = recipient_email
    msg["Subject"]  = subject
    if user_email:
        msg["Reply-To"] = user_email

    msg.attach(MIMEText(body_text, "plain"))

    # Attach PDF
    filename = (
        f"LYLO_TacticalVault_{persona_id.upper()}_"
        f"{incident_title.replace(' ', '_')[:30]}.pdf"
    )
    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(pdf_bytes)
    encoders.encode_base64(attachment)
    attachment.add_header(
        "Content-Disposition", f'attachment; filename="{filename}"'
    )
    msg.attach(attachment)

    # ── Send ─────────────────────────────────────────────────────────────────
    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls(context=context)
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, recipient_email, msg.as_string())
        log.info(
            f"[Vault] Report sent to {recipient_email[:4]}*** "
            f"persona={persona_id} incident='{incident_title[:40]}'"
        )
        return True
    except Exception as e:
        log.error(f"[Vault] send_report_to_pro failed: {e}")
        return False


# =============================================================================
# BODYGUARD SUMMARY PROMPT BUILDER
# =============================================================================

def build_incident_prompt(
    persona_id:          str,
    incident_description: str,
    metadata:            dict,
    image_count:         int = 0,
) -> str:
    """
    Builds the OpenAI prompt to generate the AI Bodyguard Summary section.
    Call this BEFORE generate_tactical_report() — pass the response as
    report_data.bodyguard_summary.

    Tone: Calm. Stern. Focused. No fluff. No generic filler.
    Voice: "Stay safe. Take the photo. I am recording the rest."

    Args:
        persona_id:           The active persona seat
        incident_description: Raw user description of what happened
        metadata:             Dict with timestamp, gps, weather keys
        image_count:          Number of images attached

    Returns:
        A system + user prompt string for a single OpenAI completion call.
    """
    persona_focus = {
        "doctor":   "triage priority, pain indicators, and urgency of medical attention",
        "lawyer":   "legal exposure, preservation of evidence, and silence protocol",
        "wealth":   "consumer rights, financial impact, and dispute escalation path",
        "mechanic": "mechanical failure root cause, safety risk, and repair cost context",
        "guardian": "security threat level, immediate protective actions, and documentation chain",
    }
    focus = persona_focus.get(persona_id, "incident facts and immediate next steps")

    gps_note = ""
    if metadata.get("gps_latitude"):
        gps_note = (
            f"GPS: {metadata['gps_latitude']}, {metadata['gps_longitude']}. "
            f"Address: {metadata.get('gps_address', 'unknown')}."
        )

    weather_note = ""
    if metadata.get("weather_condition"):
        weather_note = (
            f"Weather at time of incident: {metadata['weather_condition']}, "
            f"{metadata.get('weather_temp_f', '?')}°F."
        )

    image_note = (
        f"{image_count} photo(s) have been attached to this report as visual evidence."
        if image_count > 0
        else "No photos attached."
    )

    return f"""
SYSTEM: You are the LYLO OS Bodyguard Council. A protected party has just experienced
an incident and this summary will be printed as a formal record in their Tactical Vault PDF.

Your tone: Calm. Stern. Precise. No filler. No warmth or pleasantries.
Voice model: "Stay safe. Take the photo. I am recording the rest."
Write as if this will be read by a judge, a doctor, or an insurance adjuster.

Your task: Write a 3-5 sentence plain-English summary of this incident.
Focus on: {focus}.
Do NOT use jargon. Do NOT say "It's important to note." Do NOT say "I'm here to help."
State the facts. Name the risks. Give one clear next action.

INCIDENT DATA:
Timestamp: {metadata.get('timestamp', 'Unknown')}
{gps_note}
{weather_note}
{image_note}

USER STATEMENT:
{incident_description}

Write the Bodyguard Summary now. 3-5 sentences. Plain English. Facts only.
""".strip()
